# Configuration for Ambrosia Collective Holdings LLC
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "774654eae45e57af2f29282cc31455a6"
name = "checkout redo engine"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
