# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c6f5826368ce8cc82561c106c8ccc9b4"
name = "checkout redo engine"
application_url = "https://checkout-redo-engine.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers,read_discounts,write_discounts,read_price_rules,write_price_rules,read_metaobjects,write_metaobjects,read_themes,read_delivery_customizations,write_delivery_customizations"

[auth]
redirect_urls = [ "https://checkout-redo-engine.vercel.app/api/auth/callback", "https://checkout-redo-engine.vercel.app/api/auth", "https://localhost/api/auth/callback" ]
