# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef05a2cf8735057b2c9e043d26225eb0"
name = "checkout redo engine"
application_url = "https://checkout-redo-engine.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [ "https://checkout-redo-engine.vercel.app/api/auth/callback", "https://localhost/api/auth/callback" ]
